/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBulkInput: typeof import('./components/AppBulkInput.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    LocaleSwitcher: typeof import('./components/LocaleSwitcher.vue')['default']
    NetworkStatusIndicator: typeof import('./components/NetworkStatusIndicator.vue')['default']
    PersonnelCombobox: typeof import('./components/PersonnelCombobox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablePagination: typeof import('./components/TablePagination.vue')['default']
    UserProfileMenu: typeof import('./components/UserProfileMenu.vue')['default']
  }
}
