/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBulkInput: typeof import('./components/AppBulkInput.vue')['default']
    AppDatePicker: typeof import('./components/AppDatePicker.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    ClearanceProgressWidget: typeof import('./components/ClearanceProgressWidget.vue')['default']
    DisplayLauncher: typeof import('./components/DisplayLauncher.vue')['default']
    KioskShell: typeof import('./components/KioskShell.vue')['default']
    LocaleSwitcher: typeof import('./components/LocaleSwitcher.vue')['default']
    MultiNoField: typeof import('./components/MultiNoField.vue')['default']
    NetworkStatusIndicator: typeof import('./components/NetworkStatusIndicator.vue')['default']
    PersonnelCombobox: typeof import('./components/PersonnelCombobox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundSettingsDialog: typeof import('./components/SoundSettingsDialog.vue')['default']
    TablePagination: typeof import('./components/TablePagination.vue')['default']
    UserProfileMenu: typeof import('./components/UserProfileMenu.vue')['default']
  }
}
